#!/bin/bash
#
# bootstrap installs things.

function bootstrapTerminal() {	
	sudo -v #ask password beforehand
	source ~/.dotfiles/installscript
}


echo 'Bootstrap terminal'
echo '------------------'
echo 'You got to run `xcode-select --install` first to install the command line tools. I will be waiting'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]
then
   bootstrapTerminal
fi